Yaśomatī Nandana
fficial Name: Śrī Nama Kirtana (Chanting of the Holy Names)
Author: Bhaktivinoda Thakura
ook Name: Gitavali (Section: Nama Kirtana Song 1)
(1)
yaśomatī-nandana, braja-baro-nāgara,
gokula-rañjana kāna
gopī-parāṇa-dhana, madana-manohara,
kāliya-damana-vidhāna
(2)
amala harinām amiya-vilāsā
vipina-purandara, navīna nāgara-bora,
baṁśī-badana suvāsā
(3)
braja-jana-pālana, asura-kula-nāśana
nanda-godhana-rākhowālā
govinda mādhava, navanīta-taskara,
sundara nanda-gopālā
(4)
yāmuna-taṭa-cara, gopī-basana-hara,
rāsa-rasika, kṛpāmoya
śrī-rādhā-vallabha, bṛndābana-naṭabara,
bhakativinod-āśraya
t:
t: 1) Lord Kṛṣṇa is the beloved son of mother Yasoda; the transcendental lover in the land of Vraja; the delight of Gokula; Kana [a nickname of Kṛṣṇa]; the wealth of the lives of the gopis. He steals the mind of even Cupid and punishes the Kaliya serpent.
t: 2) These pure, holy names of Lord Hari are full of sweet, nectarean pastimes. Kṛṣṇa is the Lord of the twelve forests of Vraja, He is ever-youthful and is the best of lovers. He is always playing on a flute, and He is an excellent dresser.
t: 3) Kṛṣṇa is the protector of the inhabitants of Vraja; the destroyer of various demoniac dynasties; the keeper and tender of Nanda Maharaja's cows; the giver of pleasure to the cows, land, and spiritual senses; the husband of the goddess of fortune; the butter thief; and the beautiful cowherd boy of Nanda Maharaja.
t: 4) Kṛṣṇa wanders along the banks of the River Yamuna. He stole the garments of the young damsels of Vraja who were bathing there. He delights in the mellows of the rasa dance; He is very merciful; the lover and beloved of Śrīmati Rādhārāni; the great dancer of Vṛndāvana; and the shelter and only refuge of Thakura Bhaktivinoda.
