Rādhe Jaya Jaya Madhava Dayite
fficial Name: Śrī Radhika Stava
Author: Rupa Goswami
ook Name: Stavamala (Section: Volume 6 Song 14)
(refrain) rādhe jaya jaya mādhava-dayite gokula-taruṇī-maṇḍala-mahite
(1)
dāmodara-rati-vardhana-veśe
hari-niṣkuṭa-vṛndā-vipineśe
(2)
vṛṣabhānūdadhi-nava-śaśi-lekhe
lalitā-sakhi guṇa-ramita-viśākhe
(3)
karuṇāṁ kuru mayi karuṇā-bharite
sanaka-sanātana-varṇita-carite
t:
(Refrain) O Rādhā! O beloved of Madhava! O You who are worshiped by all the young girls of Gokula! All glories unto You! All glories unto You! (1-3) You who dress Yourself in such a way as to increase Lord Damodara's love and attachment for You! O queen of Vṛndāvana, which is the pleasure grove of Lord Hari! O new moon that has arisen from the ocean of King Vrsabhanu! O friend of Lalita! O You who make Visakha loyal to You due to Your wonderful qualities of friendliness, kindness, and faithfulness to Kṛṣṇa! O You who are filled with compassion! O You whose divine characteristics are described by the great sages Sanaka and Sanatana! O Rādhā, please be merciful to me!
